---- Create users table
--CREATE TABLE users (
--    username VARCHAR(50) NOT NULL,
--    password VARCHAR(100) NOT NULL,
--    enabled TINYINT(1) NOT NULL,
--    PRIMARY KEY (username)
--);
--
---- Create authorities table
--CREATE TABLE authorities (
--    username VARCHAR(50) NOT NULL,
--    authority VARCHAR(50) NOT NULL,
--    PRIMARY KEY (username, authority)
--);